FROM node:22-alpine3.19

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY src ./src/
COPY tools ./tools

RUN ls -a
RUN npm install --legacy-peer-deps && npm install -g nodemon

EXPOSE 4002
CMD [ "npm", "run", "dev" ]
