services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13.4-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
       # AMQP protocol port
      - 5672:5672
       # Management UI
      - 15672:15672
    networks:
      - elasticsearch_network

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch_network
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.14.3
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]  
    ports:
      - 5601:5601
    networks:
      - elasticsearch_network
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

  notifications:
    container_name: notifications_container
    build:
      context: ../notification_service
      dockerfile: Dockerfile.dev
    ports:
      - 4001:4001
    restart: always
    env_file:
      - ../notification_service/.env
    environment:
      - SERVER_PORT=4001
      - ENABLE_AMP=0
      - SMTP_PORT=587
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - APP_ICON=https://i.ibb.co/Kyp2m0t/cover.png
      - RABBITMQ_ENDPOINT=amqp://nicholas:secret@rabbitmq_container:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - EMAIL_EXCHANGE_NAME=email-notification
      - EMAIL_QUEUE_NAME=email-queue
      - EMAIL_ROUTING_KEY=email-key
      - ORDER_EXCHANGE_NAME=order-notification
      - ORDER_QUEUE_NAME=order-queue
      - ORDER_ROUTING_KEY=order-key
      - SENDER_EMAIL=erica1@ethereal.email
      - SENDER_PASSWORD=catQfEryGBTc3SvsW7
    volumes:
      - ../notification_service:/app
    networks:
      - elasticsearch_network
    depends_on:
      - elasticsearch
    
networks:
  elasticsearch_network:
    driver: bridge
