services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13.4-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
       # AMQP protocol port
      - 5672:5672
       # Management UI
      - 15672:15672

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.14.3
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
      #  
    ports:
      - 5601:5601
    networks:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

  
networks:
  elasticsearch:
    name: elasticsearch