heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
- type: http
  id: notification_service
  name: Notification Service
  schedule: '@every 5s'
  #  hosts: ["http://<your-ip>:4001/notification-health"]
  hosts: ["http://host.docker.internal:4001/notification-health"]

  check.request.method: GET
  check.response.status: [200,304]

- type: http
  id: gateway_service
  name: Gateway Service
  schedule: '@every 5s'
  #  hosts: ["http://<your-ip>:4000/gateway-health"]
  hosts: ["http://host.docker.internal:4000/gateway-health"]
  check.request.method: GET
  check.response.status: [200,304]

- type: http
  id: auth_service
  name: Auth Service
  schedule: '@every 5s'
  hosts: ["http://host.docker.internal:4002/auth-health"]
  check.request.method: GET
  check.response.status: [200,304]
#
- type: http
  id: user
  name: User Service
  schedule: '@every 5s'
  hosts: ['http://host.docker.internal:4003/user-health']
  check.request.method: GET
  check.response.status: [200,304]
#
#
- type: http
  id: gig_service
  name: Gig Service
  schedule: '@every 5s'
  #  hosts: ["http://<your-ip>:4000/gateway-health"]
  hosts: ["http://host.docker.internal:4004/gig-health"]
  check.request.method: GET
  check.response.status: [200,304]
#
#
- type: http
  id: chat_service
  name: Chat Service
  schedule: '@every 5s'
  hosts: ['http://host.docker.internal:4005/chat-health']
  check.request.method: GET
  check.response.status: [200,304]
#
- type: http
  id: order_service
  name: Order Service
  schedule: '@every 5s'
  hosts: ['http://host.docker.internal:4006/order-health']
  check.request.method: GET
  check.response.status: [200,304]

- type: http
  id: review_service
  name: Review Service
  schedule: '@every 5s'
  hosts: ['http://host.docker.internal:4007/review-health']
  check.request.method: GET
  check.response.status: [200,304]

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ['http://elasticsearch_container:9200']
#  username: 'elastic'
#  password: 'nicholas145'
