eartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
- type: http
  id: notification_service
  name: Notification Service
  schedule: '@every 5s'
  hosts: ["http://<your-ip>:4001/notification-health"]
  check.request.method: GET
  check.response.status: [200]

- type: http
  id: gateway_service
  name: Gateway Service
  schedule: '@every 5s'
  hosts: ["http://<your-ip>:4000/gateway-health"]
  check.request.method: GET
  check.response.status: [200]

- type: http
  id: auth_service
  name: Auth Service
  schedule: '@every 5s'
  hosts: ["http://<your-ip>:4002/auth-health"]
  check.request.method: GET
  check.response.status: [200]

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ['http://elasticsearch_container:9200']
  username: 'elastic'
  password: 'nicholas145'
